version = 1
SPDX-PackageName = "The Den"
SPDX-PackageSupplier = "sleepyyapril <mousetvgaming@gmail.com>
SPDX-PackageDownloadLocation = "https://www.denstation.net"

[[annotations]]
path = ["Resources/Audio/**", "Resources/Textures/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["**.txt", "**.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "MIT"