name: Run Python Script (Manual Only)

on:
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psutil

      - name: Run script
        run: python "Tools/debug_delete_later.py"
