# SPDX-FileCopyrightText: 2025 Aiden
# SPDX-FileCopyrightText: 2025 Aidenkrz
# SPDX-FileCopyrightText: 2025 MajorMoth
# SPDX-FileCopyrightText: 2025 sleepyyapril
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: 0Test
on:
  workflow_dispatch:

env:
  REUSE_MESSAGE: ${{ vars.REUSE_MESSAGE }}
  CHANGELOG_USER: ${{ vars.CHANGELOG_USER }}
  CHANGELOG_EMAIL: ${{ vars.CHANGELOG_EMAIL }}

jobs:
  update_headers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v4
        with:
          ref: ${{ vars.CHANGELOG_BRANCH }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tqdm

      - name: Run REUSE Header Update Script
        run: |
          python Tools/reuse_utilities/reuse_update_headers_from_merge.py 4a9b7dbdb492a964bacb222f8fbe3034da68956d
        working-directory: ${{ github.workspace }}
